// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace XReactor {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public static partial class GamePermRequestResponse {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_XReactor_GamePermRequestResponse__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::XReactor.GamePermRequestResponse, global::XReactor.GamePermRequestResponse.Builder> internal__static_XReactor_GamePermRequestResponse__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static GamePermRequestResponse() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "Ch1HYW1lUGVybVJlcXVlc3RSZXNwb25zZS5wcm90bxIIWFJlYWN0b3IikwEK" + 
            "F0dhbWVQZXJtUmVxdWVzdFJlc3BvbnNlEiQKCEdhbWV0eXBlGAEgAigOMhIu" + 
            "WFJlYWN0b3IuR2FtZVR5cGUSEwoLR2FtZXZlcnNpb24YAiABKAkSJgoJR2Ft" + 
            "ZXRva2VuGAMgAigOMhMuWFJlYWN0b3IuR2FtZVRva2VuEhUKDUdhbWVQZXJt" + 
            "VG9rZW4YBCACKAkqSwoIR2FtZVR5cGUSDwoLV0FSQ1JBRlRJSUkQARIJCgVE" + 
            "T1RBMhACEgsKB0NPVU5URVIQAxIHCgNXT1cQBBINCglTVEFSQ1JBRlQQBSod" + 
            "CglHYW1lVG9rZW4SBgoCT0sQARIICgRGQUlMEAJCAkgB");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_XReactor_GamePermRequestResponse__Descriptor = Descriptor.MessageTypes[0];
          internal__static_XReactor_GamePermRequestResponse__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::XReactor.GamePermRequestResponse, global::XReactor.GamePermRequestResponse.Builder>(internal__static_XReactor_GamePermRequestResponse__Descriptor,
                  new string[] { "Gametype", "Gameversion", "Gametoken", "GamePermToken", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Enums
  
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public enum GameToken {
    OK = 1,
    FAIL = 2,
  }
  
  #endregion
  
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class GamePermRequestResponse : pb::GeneratedMessage<GamePermRequestResponse, GamePermRequestResponse.Builder> {
    private GamePermRequestResponse() { }
    private static readonly GamePermRequestResponse defaultInstance = new GamePermRequestResponse().MakeReadOnly();
    private static readonly string[] _gamePermRequestResponseFieldNames = new string[] { "GamePermToken", "Gametoken", "Gametype", "Gameversion" };
    private static readonly uint[] _gamePermRequestResponseFieldTags = new uint[] { 34, 24, 8, 18 };
    public static GamePermRequestResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override GamePermRequestResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override GamePermRequestResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::XReactor.Proto.GamePermRequestResponse.internal__static_XReactor_GamePermRequestResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<GamePermRequestResponse, GamePermRequestResponse.Builder> InternalFieldAccessors {
      get { return global::XReactor.Proto.GamePermRequestResponse.internal__static_XReactor_GamePermRequestResponse__FieldAccessorTable; }
    }
    
    public const int GametypeFieldNumber = 1;
    private bool hasGametype;
    private global::XReactor.GameType gametype_ = global::XReactor.GameType.WARCRAFTIII;
    public bool HasGametype {
      get { return hasGametype; }
    }
    public global::XReactor.GameType Gametype {
      get { return gametype_; }
    }
    
    public const int GameversionFieldNumber = 2;
    private bool hasGameversion;
    private string gameversion_ = "";
    public bool HasGameversion {
      get { return hasGameversion; }
    }
    public string Gameversion {
      get { return gameversion_; }
    }
    
    public const int GametokenFieldNumber = 3;
    private bool hasGametoken;
    private global::XReactor.GameToken gametoken_ = global::XReactor.GameToken.OK;
    public bool HasGametoken {
      get { return hasGametoken; }
    }
    public global::XReactor.GameToken Gametoken {
      get { return gametoken_; }
    }
    
    public const int GamePermTokenFieldNumber = 4;
    private bool hasGamePermToken;
    private string gamePermToken_ = "";
    public bool HasGamePermToken {
      get { return hasGamePermToken; }
    }
    public string GamePermToken {
      get { return gamePermToken_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasGametype) return false;
        if (!hasGametoken) return false;
        if (!hasGamePermToken) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _gamePermRequestResponseFieldNames;
      if (hasGametype) {
        output.WriteEnum(1, field_names[2], (int) Gametype, Gametype);
      }
      if (hasGameversion) {
        output.WriteString(2, field_names[3], Gameversion);
      }
      if (hasGametoken) {
        output.WriteEnum(3, field_names[1], (int) Gametoken, Gametoken);
      }
      if (hasGamePermToken) {
        output.WriteString(4, field_names[0], GamePermToken);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasGametype) {
          size += pb::CodedOutputStream.ComputeEnumSize(1, (int) Gametype);
        }
        if (hasGameversion) {
          size += pb::CodedOutputStream.ComputeStringSize(2, Gameversion);
        }
        if (hasGametoken) {
          size += pb::CodedOutputStream.ComputeEnumSize(3, (int) Gametoken);
        }
        if (hasGamePermToken) {
          size += pb::CodedOutputStream.ComputeStringSize(4, GamePermToken);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static GamePermRequestResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GamePermRequestResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GamePermRequestResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GamePermRequestResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GamePermRequestResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GamePermRequestResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static GamePermRequestResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static GamePermRequestResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static GamePermRequestResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GamePermRequestResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private GamePermRequestResponse MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(GamePermRequestResponse prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<GamePermRequestResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(GamePermRequestResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private GamePermRequestResponse result;
      
      private GamePermRequestResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          GamePermRequestResponse original = result;
          result = new GamePermRequestResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override GamePermRequestResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::XReactor.GamePermRequestResponse.Descriptor; }
      }
      
      public override GamePermRequestResponse DefaultInstanceForType {
        get { return global::XReactor.GamePermRequestResponse.DefaultInstance; }
      }
      
      public override GamePermRequestResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is GamePermRequestResponse) {
          return MergeFrom((GamePermRequestResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(GamePermRequestResponse other) {
        if (other == global::XReactor.GamePermRequestResponse.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasGametype) {
          Gametype = other.Gametype;
        }
        if (other.HasGameversion) {
          Gameversion = other.Gameversion;
        }
        if (other.HasGametoken) {
          Gametoken = other.Gametoken;
        }
        if (other.HasGamePermToken) {
          GamePermToken = other.GamePermToken;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_gamePermRequestResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _gamePermRequestResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              object unknown;
              if(input.ReadEnum(ref result.gametype_, out unknown)) {
                result.hasGametype = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(1, (ulong)(int)unknown);
              }
              break;
            }
            case 18: {
              result.hasGameversion = input.ReadString(ref result.gameversion_);
              break;
            }
            case 24: {
              object unknown;
              if(input.ReadEnum(ref result.gametoken_, out unknown)) {
                result.hasGametoken = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(3, (ulong)(int)unknown);
              }
              break;
            }
            case 34: {
              result.hasGamePermToken = input.ReadString(ref result.gamePermToken_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasGametype {
       get { return result.hasGametype; }
      }
      public global::XReactor.GameType Gametype {
        get { return result.Gametype; }
        set { SetGametype(value); }
      }
      public Builder SetGametype(global::XReactor.GameType value) {
        PrepareBuilder();
        result.hasGametype = true;
        result.gametype_ = value;
        return this;
      }
      public Builder ClearGametype() {
        PrepareBuilder();
        result.hasGametype = false;
        result.gametype_ = global::XReactor.GameType.WARCRAFTIII;
        return this;
      }
      
      public bool HasGameversion {
        get { return result.hasGameversion; }
      }
      public string Gameversion {
        get { return result.Gameversion; }
        set { SetGameversion(value); }
      }
      public Builder SetGameversion(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasGameversion = true;
        result.gameversion_ = value;
        return this;
      }
      public Builder ClearGameversion() {
        PrepareBuilder();
        result.hasGameversion = false;
        result.gameversion_ = "";
        return this;
      }
      
      public bool HasGametoken {
       get { return result.hasGametoken; }
      }
      public global::XReactor.GameToken Gametoken {
        get { return result.Gametoken; }
        set { SetGametoken(value); }
      }
      public Builder SetGametoken(global::XReactor.GameToken value) {
        PrepareBuilder();
        result.hasGametoken = true;
        result.gametoken_ = value;
        return this;
      }
      public Builder ClearGametoken() {
        PrepareBuilder();
        result.hasGametoken = false;
        result.gametoken_ = global::XReactor.GameToken.OK;
        return this;
      }
      
      public bool HasGamePermToken {
        get { return result.hasGamePermToken; }
      }
      public string GamePermToken {
        get { return result.GamePermToken; }
        set { SetGamePermToken(value); }
      }
      public Builder SetGamePermToken(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasGamePermToken = true;
        result.gamePermToken_ = value;
        return this;
      }
      public Builder ClearGamePermToken() {
        PrepareBuilder();
        result.hasGamePermToken = false;
        result.gamePermToken_ = "";
        return this;
      }
    }
    static GamePermRequestResponse() {
      object.ReferenceEquals(global::XReactor.Proto.GamePermRequestResponse.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
