// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace XReactor {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public static partial class LoginRequestResponse {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_XReactor_LoginRequestResponse__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::XReactor.LoginRequestResponse, global::XReactor.LoginRequestResponse.Builder> internal__static_XReactor_LoginRequestResponse__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static LoginRequestResponse() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "ChpMb2dpblJlcXVlc3RSZXNwb25zZS5wcm90bxIIWFJlYWN0b3IidgoUTG9n" + 
            "aW5SZXF1ZXN0UmVzcG9uc2USEAoIVXNlcm5hbWUYASACKAkSJAoIVXNlcnR5" + 
            "cGUYAiABKA4yEi5YUmVhY3Rvci5Vc2VyVHlwZRImCglMb2dpbmNvZGUYAyAC" + 
            "KA4yEy5YUmVhY3Rvci5Mb2dpbkNvZGUqOQoIVXNlclR5cGUSCAoEVVNFUhAB" + 
            "EgkKBUFETUlOEAISDQoJTU9ERVJBVE9SEAMSCQoFTVVURUQQBCpuCglMb2dp" + 
            "bkNvZGUSEQoNTE9HSU5fU1VDQ0VTUxABEhIKDkFMUkVBRFlfTE9HR0VEEAIS" + 
            "FgoSUEFTU1dPUkRfSU5DT1JSRUNUEAMSFgoSVVNFUk5BTUVfTk9UX0ZPVU5E" + 
            "EAQSCgoGQkFOTkVEEAVCAkgB");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_XReactor_LoginRequestResponse__Descriptor = Descriptor.MessageTypes[0];
          internal__static_XReactor_LoginRequestResponse__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::XReactor.LoginRequestResponse, global::XReactor.LoginRequestResponse.Builder>(internal__static_XReactor_LoginRequestResponse__Descriptor,
                  new string[] { "Username", "Usertype", "Logincode", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Enums
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public enum UserType {
    USER = 1,
    ADMIN = 2,
    MODERATOR = 3,
    MUTED = 4,
  }
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public enum LoginCode {
    LOGIN_SUCCESS = 1,
    ALREADY_LOGGED = 2,
    PASSWORD_INCORRECT = 3,
    USERNAME_NOT_FOUND = 4,
    BANNED = 5,
  }
  
  #endregion
  
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class LoginRequestResponse : pb::GeneratedMessage<LoginRequestResponse, LoginRequestResponse.Builder> {
    private LoginRequestResponse() { }
    private static readonly LoginRequestResponse defaultInstance = new LoginRequestResponse().MakeReadOnly();
    private static readonly string[] _loginRequestResponseFieldNames = new string[] { "Logincode", "Username", "Usertype" };
    private static readonly uint[] _loginRequestResponseFieldTags = new uint[] { 24, 10, 16 };
    public static LoginRequestResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override LoginRequestResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override LoginRequestResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::XReactor.Proto.LoginRequestResponse.internal__static_XReactor_LoginRequestResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<LoginRequestResponse, LoginRequestResponse.Builder> InternalFieldAccessors {
      get { return global::XReactor.Proto.LoginRequestResponse.internal__static_XReactor_LoginRequestResponse__FieldAccessorTable; }
    }
    
    public const int UsernameFieldNumber = 1;
    private bool hasUsername;
    private string username_ = "";
    public bool HasUsername {
      get { return hasUsername; }
    }
    public string Username {
      get { return username_; }
    }
    
    public const int UsertypeFieldNumber = 2;
    private bool hasUsertype;
    private global::XReactor.UserType usertype_ = global::XReactor.UserType.USER;
    public bool HasUsertype {
      get { return hasUsertype; }
    }
    public global::XReactor.UserType Usertype {
      get { return usertype_; }
    }
    
    public const int LogincodeFieldNumber = 3;
    private bool hasLogincode;
    private global::XReactor.LoginCode logincode_ = global::XReactor.LoginCode.LOGIN_SUCCESS;
    public bool HasLogincode {
      get { return hasLogincode; }
    }
    public global::XReactor.LoginCode Logincode {
      get { return logincode_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasUsername) return false;
        if (!hasLogincode) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _loginRequestResponseFieldNames;
      if (hasUsername) {
        output.WriteString(1, field_names[1], Username);
      }
      if (hasUsertype) {
        output.WriteEnum(2, field_names[2], (int) Usertype, Usertype);
      }
      if (hasLogincode) {
        output.WriteEnum(3, field_names[0], (int) Logincode, Logincode);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasUsername) {
          size += pb::CodedOutputStream.ComputeStringSize(1, Username);
        }
        if (hasUsertype) {
          size += pb::CodedOutputStream.ComputeEnumSize(2, (int) Usertype);
        }
        if (hasLogincode) {
          size += pb::CodedOutputStream.ComputeEnumSize(3, (int) Logincode);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static LoginRequestResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static LoginRequestResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static LoginRequestResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static LoginRequestResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static LoginRequestResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static LoginRequestResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static LoginRequestResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static LoginRequestResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static LoginRequestResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static LoginRequestResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private LoginRequestResponse MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(LoginRequestResponse prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<LoginRequestResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(LoginRequestResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private LoginRequestResponse result;
      
      private LoginRequestResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          LoginRequestResponse original = result;
          result = new LoginRequestResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override LoginRequestResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::XReactor.LoginRequestResponse.Descriptor; }
      }
      
      public override LoginRequestResponse DefaultInstanceForType {
        get { return global::XReactor.LoginRequestResponse.DefaultInstance; }
      }
      
      public override LoginRequestResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is LoginRequestResponse) {
          return MergeFrom((LoginRequestResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(LoginRequestResponse other) {
        if (other == global::XReactor.LoginRequestResponse.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasUsername) {
          Username = other.Username;
        }
        if (other.HasUsertype) {
          Usertype = other.Usertype;
        }
        if (other.HasLogincode) {
          Logincode = other.Logincode;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_loginRequestResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _loginRequestResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasUsername = input.ReadString(ref result.username_);
              break;
            }
            case 16: {
              object unknown;
              if(input.ReadEnum(ref result.usertype_, out unknown)) {
                result.hasUsertype = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(2, (ulong)(int)unknown);
              }
              break;
            }
            case 24: {
              object unknown;
              if(input.ReadEnum(ref result.logincode_, out unknown)) {
                result.hasLogincode = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(3, (ulong)(int)unknown);
              }
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasUsername {
        get { return result.hasUsername; }
      }
      public string Username {
        get { return result.Username; }
        set { SetUsername(value); }
      }
      public Builder SetUsername(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasUsername = true;
        result.username_ = value;
        return this;
      }
      public Builder ClearUsername() {
        PrepareBuilder();
        result.hasUsername = false;
        result.username_ = "";
        return this;
      }
      
      public bool HasUsertype {
       get { return result.hasUsertype; }
      }
      public global::XReactor.UserType Usertype {
        get { return result.Usertype; }
        set { SetUsertype(value); }
      }
      public Builder SetUsertype(global::XReactor.UserType value) {
        PrepareBuilder();
        result.hasUsertype = true;
        result.usertype_ = value;
        return this;
      }
      public Builder ClearUsertype() {
        PrepareBuilder();
        result.hasUsertype = false;
        result.usertype_ = global::XReactor.UserType.USER;
        return this;
      }
      
      public bool HasLogincode {
       get { return result.hasLogincode; }
      }
      public global::XReactor.LoginCode Logincode {
        get { return result.Logincode; }
        set { SetLogincode(value); }
      }
      public Builder SetLogincode(global::XReactor.LoginCode value) {
        PrepareBuilder();
        result.hasLogincode = true;
        result.logincode_ = value;
        return this;
      }
      public Builder ClearLogincode() {
        PrepareBuilder();
        result.hasLogincode = false;
        result.logincode_ = global::XReactor.LoginCode.LOGIN_SUCCESS;
        return this;
      }
    }
    static LoginRequestResponse() {
      object.ReferenceEquals(global::XReactor.Proto.LoginRequestResponse.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
